# This is a basic workflow to help you get started with Actions

name: docker CI

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: |
        docker build ./ -t ghcr.io/dlgeraghty/test
    - name: ghcr login
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_PAT }}
        registry: ghcr.io
        repository: dlgeraghty/test
        tags: ${{ github.sha }}
        dockerfile: Dockerfile
