# This is a basic workflow to help you get started with Actions

name: docker CI

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }} 
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - name: Docker build
      run: |
        docker build ./ -t my-website
