# This is a basic workflow to help you get started with Actions

name: docker CI

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
